# @package _global_  # tweak 10
  # tweak 54
# runs with execution time profiling

defaults:
  - default
  # tweak 9
trainer:
  max_epochs: 1
  profiler: "simple"
  # profiler: "advanced"
  # profiler: "pytorch"  # tweak 69
