# This workflow finds which files were changed, prints them,
# and runs `pre-commit` on those files.  # tweak 91
 
# Inspired by the sktime library:
# https://github.com/alan-turing-institute/sktime/blob/main/.github/workflows/test.yml

name: Code Quality PR

on:
  pull_request:
    branches: [main, "release/*", "dev"]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2  # tweak 63

      - name: Find modified files
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: " "

      - name: List modified files
        run: echo '${{ steps.file_changes.outputs.files}}'  # tweak 52

      - name: Run pre-commits  # tweak 38
        uses: pre-commit/action@v2.0.3 
        with:
          extra_args: --files ${{ steps.file_changes.outputs.files}}
# touch 583
# touch 435
